"""Generate batch_extract.m with MATLAB single-quote syntax"""
import os

lines = []
L = lines.append

L("%% batch_extract.m - Extract ALL point clouds")
L("function batch_extract(nPer)")
L("if nargin<1, nPer=100; end")
L("script_dir = fileparts(mfilename('fullpath')); addpath(script_dir);")
L("jsonPath = fullfile(script_dir, '..', '4D', 'CCconfig_json', 'CCconfig_json.mmwave.json');")
L("para = read4DParam(jsonPath);")
L("dataRoot = fullfile(script_dir, '..', 'datasets_4Dradar');")
L("actions = {'walk','jump','swing','bend','boxing','sit','stand','run','falldown','liedown'};")

L("nR=para.ADCSamples; nL=para.numLoops; nC=para.chirpsPerCycle;")
L("nRX=para.numRXPerDevice; nD=para.numDevices; nTX=para.totalTX; nTRX=para.totalRX;")
L("r_axis=(0:nR-1)'*para.dr; vm=para.lambda/(4*para.Chirptime*nC);")
L("v_axis=((0:nL-1)-nL/2)*(2*vm/nL);")
L("rMin=max(1,round(0.5/para.dr)); rMax=min(nR,round(5/para.dr));")
L("zb=nL/2+1; range_mask=(r_axis>=0.5)&(r_axis<=5.5);")
L("rWin=hanning(nR); dWin=hanning(nL);")
L("tx0=[3,6,9,12]; tx1=[2,5,8,11]; tx2=[1,4,7,10];")
L("devs={'master','slave1','slave2','slave3'};")
L("CFAR_TF=3; SNR_DB=4; ANG_TH=1.5; MAX_D=30; N_A=128;")
L("Z_MIN=0.3; Z_MAX=2.5; X_MAX=1.5; Y_MIN=0.5; Y_MAX=6.0; fs=15; fe=60;")
L("range_mask = (r_axis>=0.5)&(r_axis<=5.5);  %% Wide range for all scenarios")

L("trainDir = fullfile(script_dir, '..', 'train_python', 'pointcloud_data');")
L("if ~exist(trainDir,'dir'), mkdir(trainDir); end")
L("dataFile = fullfile(trainDir, 'all_pointclouds.mat');")
L("if exist(dataFile,'file')")
L("    ld=load(dataFile); all_sc=ld.all_sc; all_lb=ld.all_lb; all_pc=ld.all_pc; nTot=length(all_sc);")
L("else")
L("    all_sc={}; all_lb=[]; all_pc={}; nTot=0;")
L("end")

L("fprintf('===== Batch Extract (up to %d/class) =====\\n', nPer);")

# Main loop: we need to construct this carefully
main_loop = []
main_loop.append("for a=1:length(actions)")
main_loop.append("    act=actions{a}; fprintf('\\n=== %s ===\\n',act);")
main_loop.append("    for s=1:nPer")
main_loop.append("        sc=sprintf('CCdata_%s_%04d',act,s);")
main_loop.append("        if ~exist(fullfile(dataRoot,sc),'dir'), fprintf('  End %s at %d\\n',act,s-1); break; end")
main_loop.append("        fprintf('  [%d] %s...',s,sc); tt=tic;")
main_loop.append("        adc=cell(nD,1); rdOK=true;")
main_loop.append("        for d=1:nD")
main_loop.append("            fp=fullfile(dataRoot,sc,[devs{d} '_0000_data.bin']);")
main_loop.append("            try; adc{d}=read4DRawData(fp,para,fs:fe); catch; rdOK=false; break; end")
main_loop.append("        end")
main_loop.append("        if ~rdOK, fprintf(' READ_ERR\\n'); continue; end")
main_loop.append("        nF=size(adc{1},4); if nF<5, fprintf(' FEW\\n'); continue; end")
main_loop.append("        all_pts=[];")
main_loop.append("        for fi=1:nF")
main_loop.append("            rfft=cell(nD,1); for d=1:nD, frm=squeeze(adc{d}(:,:,:,fi)); rfft{d}=fft(frm.*rWin.',[],2); end")
main_loop.append("            rc=cell(nTX,1);")
main_loop.append("            for tx=1:nTX, di=para.txChirpMap(tx,1); rt=reshape(rfft{di},nRX,nR,nC,nL); rd=squeeze(rt(:,:,tx,:)); rd=rd-mean(rd,3); rd=fft(rd.*reshape(dWin,1,1,nL),[],3); rc{tx}=fftshift(rd,3); end")
main_loop.append("            rP=zeros(nR,nL); for k=1:length(tx0), rP=rP+squeeze(mean(abs(rc{tx0(k)}).^2,1))+squeeze(mean(abs(rc{tx1(k)}).^2,1)); end; rP=rP/(2*length(tx0));")
main_loop.append("            gr=4;gd=2;tr=8;td=4;kr=2*tr+2*gr+1;kd=2*td+2*gd+1; kern=ones(kr,kd);kern(tr+1:tr+2*gr+1,td+1:td+2*gd+1)=0; nA=conv2(rP,kern,'same')/sum(kern(:)); det=rP>(nA*CFAR_TF);e=tr+gr; det(1:e,:)=false;det(end-e+1:end,:)=false;det(:,1:e)=false;det(:,end-e+1:end)=false; det(1:rMin-1,:)=false;det(rMax+1:end,:)=false;det(~range_mask,:)=false;det(:,zb-4:zb+4)=false; [dR,dD]=find(det);")
main_loop.append("            if ~isempty(dR), snr=rP(sub2ind([nR,nL],dR,dD))./(nA(sub2ind([nR,nL],dR,dD))+eps); ok=snr>10^(SNR_DB/10); if sum(ok)>MAX_D, [~,si]=sort(snr(ok),'descend');gi=find(ok);ok(gi(si(MAX_D+1:end)))=false; end; dR=dR(ok);dD=dD(ok); end")
main_loop.append("            fp=zeros(length(dR),4);nv=0;")
main_loop.append("            for i=1:length(dR)")
main_loop.append("                ri=dR(i);di=dD(i);rx32=zeros(2*nTRX,1);")
main_loop.append("                for d=1:nD, i0=(d-1)*nRX*2+1; rx32(i0:i0+nRX-1)=rc{tx0(d)}(:,ri,di); rx32(i0+nRX:i0+2*nRX-1)=rc{tx1(d)}(:,ri,di); end")
main_loop.append("                asp=fftshift(abs(fft(rx32,N_A)));[pk,pi]=max(asp); if pk<ANG_TH*median(asp),continue;end")
main_loop.append("                sA=(pi-N_A/2-1)/(N_A/2);sA=max(-1,min(1,sA));az=asind(sA);")
main_loop.append("                pd=zeros(nTRX,1);aw=zeros(nTRX,1);")
main_loop.append("                for d=1:nD, i0=(d-1)*nRX+1; t0=rc{tx0(d)}(:,ri,di);t2=rc{tx2(d)}(:,ri,di); pd(i0:i0+nRX-1)=angle(t2.*conj(t0));aw(i0:i0+nRX-1)=abs(t0); end")
main_loop.append("                aw=aw/(sum(aw)+eps);ph=sum(pd.*aw); sE=ph/pi;sE=max(-1,min(1,sE));el=asind(sE);")
main_loop.append("                rM=r_axis(ri);vM=v_axis(di); xM=rM*cosd(el)*sind(az);yM=rM*cosd(el)*cosd(az);zM=rM*sind(el);")
main_loop.append("                if zM<Z_MIN||zM>Z_MAX||abs(xM)>X_MAX||yM<Y_MIN||yM>Y_MAX,continue;end")
main_loop.append("                nv=nv+1;fp(nv,:)=[xM,yM,zM,vM];")
main_loop.append("            end")
main_loop.append("            all_pts=[all_pts; fp(1:nv,:)];")
main_loop.append("        end")
main_loop.append("        nTot=nTot+1; all_sc{nTot}=sc; all_lb(nTot)=a-1; all_pc{nTot}=all_pts;")
main_loop.append("        save(dataFile,'all_sc','all_lb','all_pc','actions','-v7.3');")
main_loop.append("        fprintf(' %df %dpts %.1fs\\n',nF,size(all_pts,1),toc(tt));")
main_loop.append("    end")
main_loop.append("end")
main_loop.append("fprintf('\\n===== DONE: %d scenarios =====\\n',nTot);")
main_loop.append("end")

for line in main_loop:
    L(line)

outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'batch_extract.m')
with open(outpath, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f'Written {len(lines)} lines to {outpath}')
